#!/usr/bin/env python3
"""Write include/pkbn/fx_ids.h (effect names only, no graphics) from fx_curated.py."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fx_curated import FX
L = ['// GENERATED by tools/gen_fx_ids.py from tools/fx_curated.py. Names of BN6 effect sprites (bn6f category:index anim).',
     '#ifndef GUARD_PKBN_FX_IDS_H', '#define GUARD_PKBN_FX_IDS_H', '', 'enum PkbnFxId', '{']
for name, cat, idx, anim in FX:
    L.append('    FX_%s, // bn6f %d:0x%02x anim %d' % (name, cat, idx, anim))
L += ['    FX_COUNT', '};', '', '#endif // GUARD_PKBN_FX_IDS_H', '']
open(sys.argv[1], 'w').write('\n'.join(L))
