#!/usr/bin/env python3
"""Generate src/pkbn/move_table.c from attacks_curated.py + lanes_curated.py.

usage: python3 tools/gen_move_table.py <pc_port root>
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from attacks_curated import ATTACKS, KINDS
from lanes_curated import MOVES as LANE_MOVES, REMOVED

root = sys.argv[1] if len(sys.argv) > 1 else '.'
bm = open(f'{root}/src/data/battle_moves.h').read()
order = [n[5:] for n in re.findall(r'\[(MOVE_\w+)\]\s*=\s*\{', bm) if n != 'MOVE_NONE']

PATTERNS = {'plus': 'BLAST_PLUS', 'x': 'BLAST_X', 'square': 'BLAST_SQUARE', 'single': 'BLAST_SINGLE'}
FLAGS = {'slow': 'GF_SLOW', 'fast': 'GF_FAST', 'invuln': 'GF_INVULN', 'hold': 'GF_HOLD', 'push': 'GF_PUSH',
         'recharge': 'GF_RECHARGE'}

def parse_attack(spec):
    toks = spec.split()
    kind, pattern, hits, windup, rows, flags = toks[0], 'BLAST_PLUS', '1', '0', '1', []
    for t in toks[1:]:
        if t in PATTERNS: pattern = PATTERNS[t]
        elif t in FLAGS: flags.append(FLAGS[t])
        elif t.startswith('hits='):
            v = t[5:]; hits = 'HITS_2_TO_5' if v == '2-5' else 'HITS_PARTY' if v == 'party' else v
        elif t.startswith('charge='): windup = t[7:]
        elif t.startswith('rows='): rows = t[5:]
        else: raise SystemExit(f'unknown modifier {t} in {spec}')
    return kind, pattern, hits, windup, rows, ' | '.join(flags) or '0'

def parse_lanes(spec):
    out = []
    for t in spec.split():
        out.append('LANE_WILD' if t == '*' else f"LANE('{t[0]}')")
    return out

lines = ['// GENERATED by tools/gen_move_table.py from tools/attacks_curated.py and tools/lanes_curated.py.',
         '// Do not edit by hand: change the curated files and regenerate.',
         '#include "global.h"', '#include "constants/moves.h"', '#include "pkbn/move_table.h"', '',
         'const struct PkbnMoveInfo gPkbnMoveInfo[MOVES_COUNT] =', '{']
for m in order:
    kind, pattern, hits, windup, rows, flags = parse_attack(ATTACKS[m])
    removed = m in REMOVED
    lanes = [] if removed or m not in LANE_MOVES else parse_lanes(LANE_MOVES[m])
    lanes_c = '{' + ', '.join(lanes) + '}' if lanes else '{0}'
    lines.append(f'    [MOVE_{m}] = {{ GK_{kind}, {pattern}, {hits}, {windup}, {rows}, {flags}, {len(lanes)}, {lanes_c} }},'
                 + ('  // removed (review)' if removed else ''))
lines.append('};')
lines.append('')
lines.append('const char *const gPkbnKindNames[GK_COUNT] =')
lines.append('{')
for k in KINDS:
    lines.append(f'    [GK_{k}] = "{k}",')
lines.append('};')
open(f'{root}/src/pkbn/move_table.c', 'w').write('\n'.join(lines) + '\n')

h = ['// GENERATED by tools/gen_move_table.py. Kinds are documented in tools/attacks_curated.py (KINDS).',
     '#ifndef GUARD_PKBN_MOVE_TABLE_H', '#define GUARD_PKBN_MOVE_TABLE_H', '', 'enum', '{']
for k, (desc, bn) in KINDS.items():
    h.append(f'    GK_{k}, // {desc}' + (f' [{bn}]' if bn else ''))
h += ['    GK_COUNT', '};', '',
      'enum { BLAST_PLUS, BLAST_X, BLAST_SQUARE, BLAST_SINGLE };', '',
      '#define HITS_2_TO_5 254 // Gen 3 multi-hit odds',
      '#define HITS_PARTY  255 // Beat Up: one hit per healthy party member', '',
      '#define GF_SLOW     (1 << 0)',
      '#define GF_FAST     (1 << 1)',
      '#define GF_INVULN   (1 << 2)',
      '#define GF_HOLD     (1 << 3)',
      '#define GF_PUSH     (1 << 4)',
      '#define GF_RECHARGE (1 << 5)', '',
      "#define LANE(c)   ((c) - 'A')",
      '#define LANE_WILD 26', '',
      'struct PkbnMoveInfo',
      '{',
      '    u8 kind;',
      '    u8 pattern;   // BOMB blast pattern',
      '    u8 hits;      // 1.., HITS_2_TO_5, HITS_PARTY',
      '    u8 windup;    // charge frames before it fires',
      '    u8 rows;      // CANNON / WAVE / SHOCKWAVE: 1 or 3',
      '    u8 flags;     // GF_*',
      '    u8 laneCount; // 0 = not a chip (removed by review or not on the grid)',
      '    u8 lanes[4];  // one letter per copy, in order; LANE_WILD = *',
      '};', '',
      'extern const struct PkbnMoveInfo gPkbnMoveInfo[];',
      'extern const char *const gPkbnKindNames[];', '',
      '#endif // GUARD_PKBN_MOVE_TABLE_H']
open(f'{root}/include/pkbn/move_table.h', 'w').write('\n'.join(h) + '\n')
print('wrote', len(order), 'moves')
