#!/usr/bin/env python3
"""Generate src/pkbn/ncp_table.c and include/pkbn/ncp_table.h from tools/navicust_curated.py.

Usage: gen_navicust.py <host dir>
The tables contain only names, shapes (BN6 shapes are data read from bn6f, cited per program) and numbers.
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from navicust_curated import PROGRAMS, ABILITY_SIZE_1, ABILITY_SIZE_3, ABILITY_GRANTS

host = sys.argv[1]
EFFECTS = ['NONE', 'SUPER_ARMOR', 'HAND', 'FIRST_BARRIER', 'FLOAT_SHOES', 'AIR_SHOES', 'UNDER_SHIRT', 'BUG_STOP',
           'BUST_PACK', 'BUSTER_ATK', 'BUSTER_SPEED', 'BUSTER_CHARGE', 'HP_PCT', 'STAT_PCT', 'QUICK_CLAW', 'KINGS_ROCK',
           'SCOPE_LENS', 'BRIGHT_POWDER', 'LEFTOVERS', 'SHELL_BELL', 'FOCUS_BAND', 'CHOICE_BAND', 'LUCKY_EGG',
           'AMULET_COIN', 'TYPE_BOOST']
CONDS = ['COOL', 'BEAUTY', 'CUTE', 'SMART', 'TOUGH']
STATS = {'ATK': 'STAT_ATK', 'DEF': 'STAT_DEF', 'SPATK': 'STAT_SPATK', 'SPDEF': 'STAT_SPDEF', 'SPEED': 'STAT_SPEED'}
GRANT_FLAGS = {'FLOAT_SHOES': 'NCPF_FLOAT_SHOES', 'AIR_SHOES': 'NCPF_AIR_SHOES', 'UNDER_SHIRT': 'NCPF_UNDER_SHIRT',
               'SUPER_ARMOR': 'NCPF_SUPER_ARMOR'}

def shape_c(rows):
    h = len(rows); w = max(len(r) for r in rows)
    assert w <= 5 and h <= 5, rows
    bits = []
    for r in rows:
        b = 0
        for x, ch in enumerate(r):
            if ch == '#': b |= 1 << x
        bits.append(b)
    bits += [0] * (5 - len(bits))
    return '{%d, %d, {%s}}' % (w, h, ', '.join(str(b) for b in bits))

H = ['// GENERATED by tools/gen_navicust.py from tools/navicust_curated.py - do not edit.',
     '#ifndef GUARD_PKBN_NCP_TABLE_H', '#define GUARD_PKBN_NCP_TABLE_H', '', '#include "global.h"', '',
     'enum PkbnNcpEffect', '{'] + ['    NCPE_%s,' % e for e in EFFECTS] + ['    NCPE_COUNT', '};', '',
     'enum { NCP_COND_COOL, NCP_COND_BEAUTY, NCP_COND_CUTE, NCP_COND_SMART, NCP_COND_TOUGH, NCP_COND_COUNT };', '',
     '// Program effects an ability grants (BN-style twins), and flags in compiled results.',
     '#define NCPF_SUPER_ARMOR (1 << 0)', '#define NCPF_FLOAT_SHOES (1 << 1)', '#define NCPF_AIR_SHOES   (1 << 2)',
     '#define NCPF_UNDER_SHIRT (1 << 3)', '',
     'struct PkbnNcpShape { u8 w, h; u8 rows[5]; }; // rows[y] bit x = cell', '',
     'struct PkbnNcp',
     '{',
     '    const char *name;',
     '    const char *desc;',
     '    u8 effect;        // NCPE_*',
     '    u8 arg;           // STAT_* for STAT_PCT, TYPE_* for TYPE_BOOST',
     '    s16 value;',
     '    bool8 plus;       // plus part: must not touch the command line',
     '    u8 group;         // exclusive group (0 = none)',
     '    u8 bug;           // bug type it causes',
     '    u8 cond;          // NCP_COND_*: the Pokéblock condition that compresses it',
     '    u8 typeCount;',
     '    u8 types[3];      // colour variants',
     '    struct PkbnNcpShape shape, cshape;',
     '};', '',
     '#define NCP_COUNT %d' % len(PROGRAMS),
     'extern const struct PkbnNcp gPkbnNcps[NCP_COUNT];',
     'extern const u8 gPkbnAbilityCells[];   // 1..3 cells of the fixed ability program, by ABILITY_*',
     'extern const u8 gPkbnAbilityGrants[];  // NCPF_* an ability grants', '',
     '#endif // GUARD_PKBN_NCP_TABLE_H', '']
C = ['// GENERATED by tools/gen_navicust.py from tools/navicust_curated.py - do not edit.',
     '#include "global.h"', '#include "constants/abilities.h"', '#include "constants/pokemon.h"', '#include "pkbn/ncp_table.h"', '',
     'const struct PkbnNcp gPkbnNcps[NCP_COUNT] =', '{']
for p in PROGRAMS:
    eff = p['effect']; kind = eff[0]; arg = '0'; value = eff[-1] if len(eff) > 1 else 0
    if kind == 'STAT_PCT': arg = STATS[eff[1]]
    if kind == 'TYPE_BOOST': arg = 'TYPE_' + eff[1]
    types = ['TYPE_' + t for t in p['types']]
    C.append('    { // %s' % p['src'])
    C.append('        "%s", "%s", NCPE_%s, %s, %d, %s, %d, %d, NCP_COND_%s, %d, {%s}, %s, %s' % (
        p['name'], p['desc'].replace('"', '\\"'), kind, arg, value, 'TRUE' if p['plus'] else 'FALSE', p['group'],
        p['bug'], p['cond'], len(types), ', '.join(types), shape_c(p['shape']), shape_c(p['cshape'])))
    C.append('    },')
C.append('};')
C.append('')
abil = [l.split()[1] for l in open(os.path.join(host, 'include/constants/abilities.h')) if l.startswith('#define ABILITY_')
        and l.split()[1] != 'ABILITIES_COUNT']
C.append('const u8 gPkbnAbilityCells[ABILITIES_COUNT] =')
C.append('{')
for a in abil:
    n = a[len('ABILITY_'):]
    if n == 'NONE': continue
    C.append('    [%s] = %d,' % (a, 3 if n in ABILITY_SIZE_3 else 1 if n in ABILITY_SIZE_1 else 2))
C.append('};')
C.append('')
C.append('const u8 gPkbnAbilityGrants[ABILITIES_COUNT] =')
C.append('{')
for n, g in ABILITY_GRANTS.items():
    C.append('    [ABILITY_%s] = %s,' % (n, ' | '.join(GRANT_FLAGS[x] for x in g)))
C.append('};')
open(os.path.join(host, 'include/pkbn/ncp_table.h'), 'w').write('\n'.join(H))
open(os.path.join(host, 'src/pkbn/ncp_table.c'), 'w').write('\n'.join(C) + '\n')
print('navicust: %d programs, %d abilities' % (len(PROGRAMS), len(abil) - 1))
