#!/usr/bin/env python3
"""Generates src/pkbn/chip_data.c / include/pkbn/chip_data.h (design 08 §11-12, POC-10).

  gPkbnMoveMB[move]               chip memory (MB), tools/chip_memory.py rules
  gPkbnCanLearn[species][bytes]   "can learn" bitsets: level-up (pre-evolutions included), TM/HM, tutor and the
                                  family's egg moves - Khaled's rule of 2026-10-05: anyone that can learn a move
                                  can use its chip.
Everything is read from the port's own data (run from the host root):
  python3 tools/gen_chip_data.py [host_root]
"""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
root = sys.argv[1] if len(sys.argv) > 1 else '.'
os.chdir(root)
from chip_memory import load as load_moves, mb
import shared_folder_sim as sim   # load_species(): the learnset reader shared with the simulation

moves = load_moves('src/data/battle_moves.h')
ids = {m.group(1): int(m.group(2)) for m in re.finditer(r'#define MOVE_(\w+) (\d+)\n', open('include/constants/moves.h').read())}
count = ids.get('COUNT') or int(re.search(r'#define MOVES_COUNT (\d+)', open('include/constants/moves.h').read()).group(1))
nbytes = (count + 7) // 8
types, compat, final = sim.load_species()

out = ['// GENERATED by tools/gen_chip_data.py from src/data (learnsets, battle_moves) - do not edit.',
       '#include "global.h"', '#include "constants/species.h"', '#include "constants/moves.h"', '#include "pkbn/chip_data.h"', '',
       'const u8 gPkbnMoveMB[MOVES_COUNT] =', '{']
for name, mid in sorted(ids.items(), key=lambda x: x[1]):
    if name in moves and 0 < mid < count:
        out.append('    [MOVE_%s] = %d,' % (name, min(99, mb(moves[name]))))
out += ['};', '', 'const u8 gPkbnCanLearn[NUM_SPECIES][CHIP_LEARN_BYTES] =', '{']
for sp in sorted(compat):
    if sp in ('NONE', 'EGG'):
        continue
    bits = [0] * nbytes
    for mv in compat[sp]:
        if mv in ids and ids[mv] < count:
            bits[ids[mv] // 8] |= 1 << (ids[mv] % 8)
    if any(bits):
        out.append('    [SPECIES_%s] = {%s},' % (sp, ', '.join(str(b) for b in bits)))
out += ['};', '']
open('src/pkbn/chip_data.c', 'w').write('\n'.join(out))
open('include/pkbn/chip_data.h', 'w').write('''// GENERATED by tools/gen_chip_data.py - do not edit.
#ifndef GUARD_PKBN_CHIP_DATA_H
#define GUARD_PKBN_CHIP_DATA_H
#include "constants/moves.h"
#define CHIP_LEARN_BYTES %d
extern const u8 gPkbnMoveMB[MOVES_COUNT];
extern const u8 gPkbnCanLearn[][CHIP_LEARN_BYTES];
#endif // GUARD_PKBN_CHIP_DATA_H
''' % nbytes)
print('chip_data: %d moves, %d species, %d bytes per species' % (count, sum(1 for s in compat if s not in ('NONE', 'EGG')), nbytes))
