#!/usr/bin/env python3
"""Validate the curated lanes against Emerald data and simulate chains with real learnsets.

usage: python3 tools/lanes_report.py [--root upstream/pokeemerald-pc_port] [--csv data/lanes.csv] [--md research/lanes_report.md]
"""
import argparse, collections, random, re, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lanes_curated import LANES, MOVES, PROGRAM_ADVANCES, REMOVED

ap = argparse.ArgumentParser()
ap.add_argument('--root', default='upstream/pokeemerald-pc_port')
ap.add_argument('--csv', default=None)
ap.add_argument('--md', default=None)
a = ap.parse_args()
R = a.root

bm = open(f'{R}/src/data/battle_moves.h').read()
MV = {n[5:]: dict(re.findall(r'\.(\w+)\s*=\s*([^,\n]+)', b))
      for n, b in re.findall(r'\[(MOVE_\w+)\]\s*=\s*\{(.*?)\n    \}', bm, re.S)}
MV.pop('NONE', None)
cs = open(f'{R}/src/data/contest_moves.h').read().replace('[MOVE_NONE] = {0},', '')
CONTEST = {}
for n, b in re.findall(r'\[(MOVE_\w+)\]\s*=\s*\{(.*?)\n    \}', cs, re.S):
    st = re.search(r'comboStarterId\s*=\s*(\w+)', b)
    cm = re.search(r'comboMoves\s*=\s*\{([^}]*)\}', b)
    CONTEST[n[5:]] = (st.group(1) if st else '0',
                      [x.strip() for x in cm.group(1).split(',') if x.strip() not in ('', '0')] if cm else [])
STARTER_OF = {v[0]: k for k, v in CONTEST.items() if v[0] != '0'}
COMBOS = [(STARTER_OF[g], m) for m, (_, gs) in CONTEST.items() for g in gs if g in STARTER_OF]

out = []
def p(*x):
    out.append(' '.join(str(y) for y in x))

def parse(spec):
    toks = spec.split()
    star = '*' in toks
    roles = [(t[0], t[1]) for t in toks if t != '*']
    return roles, star

def strong(m):
    d = MV[m]; return int(d['power']) >= 90 or (int(d['pp']) <= 5 and int(d['power']) > 1)
def weak_or_status(m):
    d = MV[m]; return int(d['power']) <= 50
EXCEPTIONS_MULTI = {'SOLAR_BEAM', 'TRI_ATTACK', 'WEATHER_BALL', 'THUNDER', 'RAIN_DANCE', 'DREAM_EATER'}

# ---------------- validation ----------------
problems = []
missing = [m for m in MV if m not in MOVES and m not in REMOVED and m != 'STRUGGLE']
extra = [m for m in list(MOVES) + list(REMOVED) if m not in MV]
if missing: problems.append(f'moves without lanes: {missing}')
if extra: problems.append(f'unknown moves: {extra}')
for m, spec in MOVES.items():
    roles, star = parse(spec)
    if any(l not in LANES for l, _ in roles): problems.append(f'{m}: unknown lane')
    if star and not weak_or_status(m): problems.append(f'{m}: wildcard on a move stronger than 50 power')
    if strong(m) and len(roles) > 1 and m not in EXCEPTIONS_MULTI and int(MV[m]['power']) > 0:
        problems.append(f'{m}: strong move with {len(roles)} letters')
for name, recipe, _ in PROGRAM_ADVANCES:
    common = None
    for m in recipe:
        L = {l for l, _ in parse(MOVES[m])[0]}
        common = L if common is None else common & L
    if not common: problems.append(f'PA {name}: recipe has no shared letter')
    # with one letter per copy (copy k = k-th token), some combination of copies must share a letter
    per = []
    for m in recipe:
        toks = [t if t == '*' else t[0] for t in MOVES[m].split()]
        pp = int(MV[m]['pp']); n = 3 if pp >= 30 else 2 if pp >= 15 else 1
        per.append({toks[k % len(toks)] for k in range(n)})
    if not any(all(L in s_ or '*' in s_ for s_ in per) for L in LANES):
        problems.append(f'PA {name}: no set of chip copies shares a letter ({per})')

p('# Lanes report (generated by tools/lanes_report.py)')
p()
p('## Validation')
p('- moves covered:', len([m for m in MV if m in MOVES]), 'of', len(MV) - 1, '(Struggle excluded)')
p('- problems:', 'none' if not problems else '')
for x in problems: p('  -', x)

# ---------------- lane stats ----------------
p()
p('## Lanes')
p('| Lane | Name | Moves | setup / payoff / link | Types | Example chain |')
p('|---|---|---|---|---|---|')
by = collections.defaultdict(list)
for m, spec in MOVES.items():
    for l, r in parse(spec)[0]:
        by[l].append((m, r))
for l in sorted(LANES):
    ms = by[l]
    roles = collections.Counter(r for _, r in ms)
    types = sorted({MV[m]['type'][5:].title() for m, _ in ms})
    setups = [m for m, r in ms if r == 's']
    pays = sorted([m for m, r in ms if r == 'p'], key=lambda m: -int(MV[m]['power']))
    ex = ''
    if setups and pays:
        ex = f'{setups[0].title()} -> {pays[min(1, len(pays)-1)].title()} -> {pays[0].title()}'
    p(f'| {l} | {LANES[l][0]} | {len(ms)} | {roles["s"]} / {roles["p"]} / {roles["x"]} | {len(types)} | {ex.replace("_", " ")} |')

# letter count distribution vs BN6
dist = collections.Counter(len(parse(s)[0]) for s in MOVES.values())
stars = sum(1 for s in MOVES.values() if parse(s)[1])
p()
p('## Letters per move (BN6 named chips for comparison: 0:17, 1:90, 2:20, 3:118, 4:110; `*` on 152/355)')
p('- ours:', ', '.join(f'{k} letters: {v}' for k, v in sorted(dist.items())), f'; `*` allowed on {stars}/{len(MOVES)}')
p('- pure wildcards (copy / variable moves):', ', '.join(m.title().replace('_', ' ') for m, s in MOVES.items() if s.strip() == '*'))

# ---------------- contest combos preserved? ----------------
kept = 0
for s_, f in COMBOS:
    if s_ in MOVES and f in MOVES:
        Ls = {l for l, _ in parse(MOVES[s_])[0]}; Lf = {l for l, _ in parse(MOVES[f])[0]}
        if Ls & Lf or parse(MOVES[s_])[1] or parse(MOVES[f])[1]:
            kept += 1
p()
p(f'## Emerald contest combos that can be chained under these lanes: {kept} of {len(COMBOS)}')

# ---------------- Program Advances ----------------
p()
p('## Program Advances (exact 3-move order in one chain)')
p('| PA | Recipe | Shared letter | New move |')
p('|---|---|---|---|')
for name, recipe, desc in PROGRAM_ADVANCES:
    common = set.intersection(*[{l for l, _ in parse(MOVES[m])[0]} for m in recipe])
    p(f'| {name} | {" -> ".join(m.title().replace("_", " ") for m in recipe)} | {"/".join(sorted(common))} | {desc} |')

# ---------------- simulation with real learnsets ----------------
ls = open(f'{R}/src/data/pokemon/level_up_learnsets.h').read()
def moveset(species, level):
    camel = ''.join(w.capitalize() for w in species.split('_'))
    m = re.search(r's%sLevelUpLearnset\[\] = \{(.*?)\};' % camel, ls, re.S)
    moves = []
    for lv, mv in re.findall(r'LEVEL_UP_MOVE\(\s*(\d+),\s*MOVE_(\w+)\)', m.group(1)):
        if int(lv) <= level and mv not in moves:
            moves.append(mv)
    return moves[-4:]

def copies(m):
    pp = int(MV[m]['pp']); return 3 if pp >= 30 else 2 if pp >= 15 else 1

def folder(party, union):
    chips = []
    for i, (sp, lv) in enumerate(party):
        for m in moveset(sp, lv):
            if m in REMOVED: continue
            letters = [t if t == '*' else t[0] for t in MOVES[m].split()]  # token order = copy order
            for k in range(copies(m)):
                if union:
                    chips.append((i, m, frozenset(letters)))
                else:
                    chips.append((i, m, frozenset([letters[k % len(letters)]])))
    return chips[:30]

def best_chain(hand):
    best = 1
    letters = set().union(*[c[2] for c in hand]) - {'*'}
    wild = sum(1 for c in hand if '*' in c[2] and len(c[2]) == 1)
    for L in letters:
        n = sum(1 for c in hand if L in c[2] or '*' in c[2])
        best = max(best, n)
    best = max(best, wild + (1 if wild < len(hand) else 0), max(collections.Counter(c[1] for c in hand).values()))
    return min(best, len(hand))

PARTIES = {
 'Early solo  (Mudkip 12)':             [('MUDKIP', 12)],
 'Early solo  (Torchic 12)':            [('TORCHIC', 12)],
 'Early solo  (Treecko 12)':            [('TREECKO', 12)],
 'Early party (Mudkip, Wingull, Zigzagoon @12)': [('MUDKIP', 12), ('WINGULL', 12), ('ZIGZAGOON', 12)],
 'Early party (Torchic, Ralts, Poochyena @12)':  [('TORCHIC', 12), ('RALTS', 12), ('POOCHYENA', 12)],
 'Mid party   (Marshtomp, Kirlia, Swellow, Breloom, Manectric @28)':
     [('MARSHTOMP', 28), ('KIRLIA', 28), ('SWELLOW', 28), ('BRELOOM', 28), ('MANECTRIC', 28)],
 'Late party  (Swampert, Gardevoir, Swellow, Breloom, Manectric, Camerupt @45)':
     [('SWAMPERT', 45), ('GARDEVOIR', 45), ('SWELLOW', 45), ('BRELOOM', 45), ('MANECTRIC', 45), ('CAMERUPT', 45)],
}
random.seed(7)
p()
p('## Simulated chains (random 5-chip hands; benched chips playable = they switch in; wildcard Switch slot not counted)')
p('| Party | Folder | Moves seen | chips/turn (one letter per copy) | hands with 2+ | chips/turn (all legal letters) |')
p('|---|---|---|---|---|---|')
for label, party in PARTIES.items():
    res = []
    for union in (False, True):
        ch = folder(party, union)
        N = 4000
        vals = [best_chain(random.sample(ch, min(5, len(ch)))) for _ in range(N)]
        res.append((len(ch), sum(vals) / N, 100 * sum(v >= 2 for v in vals) / N))
    seen = sorted({m.title().replace('_', ' ') for sp, lv in party for m in moveset(sp, lv)})
    p(f'| {label} | {res[0][0]} | {", ".join(seen)} | {res[0][1]:.2f} | {res[0][2]:.0f}% | {res[1][1]:.2f} |')

text = '\n'.join(out)
print(text)
if a.md:
    open(a.md, 'w').write(text + '\n')
if a.csv:
    with open(a.csv, 'w') as f:
        f.write('move,type,power,pp,letters,wildcard,roles,contest_starter,contest_followups\n')
        for m in MV:
            if m not in MOVES: continue
            roles, star = parse(MOVES[m])
            f.write(f'{m},{MV[m]["type"][5:]},{MV[m]["power"]},{MV[m]["pp"]},{"".join(l for l, _ in roles)},{"Y" if star else ""},'
                    f'{" ".join(l + r for l, r in roles)},{CONTEST.get(m, ("0", []))[0].replace("COMBO_STARTER_", "")},'
                    f'{" ".join(g.replace("COMBO_STARTER_", "") for g in CONTEST.get(m, ("0", []))[1])}\n')
